id: P008088
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18488
  title: མན་ངག་རིན་པོ་ཆེའི་མཛོད་ཀྱི་སྐྱུད་བྱང་གདམས་ངག་ནོར་བུའི་གཏེར་མཛོད།
  author: ''
  volumes:
    8f5df5a454f74310851f420fd1e617e9:
      image_group_id: I1KG18502
      title: ''
      volume_number: 1
      total_pages: 516
    8e94fea33d7a4808a38b0a4605f5b49d:
      image_group_id: I1KG18503
      title: ''
      volume_number: 2
      total_pages: 532
ebook_metadata:
  title: མན་ངག་རིན་པོ་ཆེའི་མཛོད་ཀྱི་སྐྱུད་བྱང་གདམས་ངག་ནོར་བུའི་གཏེར་མཛོད།
  author: ''
  sku: P008088
  cover: cover.jpg
  layers:
  - pagination
