id: I4CC8EF92
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:57:31+00:00'
last_modified: '2022-06-09T04:24:44.483898+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18488
  title: མན་ངག་རིན་པོ་ཆེའི་མཛོད་ཀྱི་སྐྱུད་བྱང་གདམས་ངག་ནོར་བུའི་གཏེར་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '9315':
      image_group_id: I1KG18502
      title: Volume 1 of man ngag rin po che'i mdzod kyi skyud byang gdams ngag nor
        bu'i gter mdzod/
      total_pages: 516
      order: 1
      base_file: 9315.txt
    C01C:
      image_group_id: I1KG18503
      title: Volume 2 of man ngag rin po che'i mdzod kyi skyud byang gdams ngag nor
        bu'i gter mdzod/
      total_pages: 532
      order: 2
      base_file: C01C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
